## Playing with Tensors

In [5]:
import torch
import numpy as np
np.set_printoptions(precision=3)

a = [1,2,3]

b= np.array([4,5,6],dtype=np.int32)

t_a = torch.Tensor(a)

t_b = torch.from_numpy(b)

print(t_a)
print(t_b)

SyntaxError: invalid syntax (__init__.py, line 302)

Math Operations to tensors:



Applying mathematical operations, in particular linear algebra operations, is necessary for building most machine learning models. In this subsection, we will cover some widely used linear algebra operations, such as element-wise product, matrix multiplication, and computing the norm of a tensor

In [4]:
torch.manual_seed(1)
t1 = 2 * torch.rand(5,2) - 1 # between range 1 and -1
t2 = torch.normal(mean=0,std=1,size=(5,2)) # Standard normal distribution
t2

NameError: name 'torch' is not defined

Reshaping a tensor

In [3]:
t = torch.zeros(30)
t_reshape = t.reshape(5,6)
print(t_reshape.shape)

torch.Size([5, 6])


## Creating a pytorch dataloader

. As a simple example, consider the following code, which creates a dataset from a list of values from 0 to 5:

In [4]:
from torch.utils.data import DataLoader

t = torch.arange(12,dtype=torch.float32)
data_loader = DataLoader(t)

for item in data_loader:
    print(item)

tensor([0.])
tensor([1.])
tensor([2.])
tensor([3.])
tensor([4.])
tensor([5.])
tensor([6.])
tensor([7.])
tensor([8.])
tensor([9.])
tensor([10.])
tensor([11.])


If we want to create batches from this dataset, with a desired batch size of 3, we can do this with the batch_size argument as follows:

For 12 tensors:

In [5]:
data_loader = DataLoader(t,batch_size = 4 , drop_last= False)
for i,batch in enumerate(data_loader,1):
    print(f"batch {i}",batch)

batch 1 tensor([0., 1., 2., 3.])
batch 2 tensor([4., 5., 6., 7.])
batch 3 tensor([ 8.,  9., 10., 11.])


#### Combining multiple tensors

In [6]:
from torch.utils.data import Dataset

class JoinData(Dataset):
    def __init__(self,x,y):
        self.x = x
        self.y = y
    def __len__(self):
        return len(self.x)
    def __getitem__(self,idx)"""  """:
        return self.x[idx],self.y[idx]

torch.manual_seed(1)
t_x = torch.rand([4,3],dtype=torch.float64)
t_y = torch.arange(4)

jointData = JoinData(t_x,t_y)

for example in jointData:
    print(f" x: {example[0]}, y: {example[1]}")

 x: tensor([0.0611, 0.2246, 0.2343], dtype=torch.float64), y: 0
 x: tensor([0.1771, 0.5561, 0.1094], dtype=torch.float64), y: 1
 x: tensor([0.4609, 0.7084, 0.5798], dtype=torch.float64), y: 2
 x: tensor([0.4967, 0.5104, 0.3295], dtype=torch.float64), y: 3


Suffle, batch and Repeat

In [7]:
torch.manual_seed(1)

data_loader = DataLoader(dataset=jointData,batch_size=2,shuffle=True)

for i,batch in enumerate(data_loader,1):
    print(f"Batch {i}:, x: {batch[0]} , y : {batch[1]}")

Batch 1:, x: tensor([[0.4609, 0.7084, 0.5798],
        [0.0611, 0.2246, 0.2343]], dtype=torch.float64) , y : tensor([2, 0])
Batch 2:, x: tensor([[0.1771, 0.5561, 0.1094],
        [0.4967, 0.5104, 0.3295]], dtype=torch.float64) , y : tensor([1, 3])


In [8]:
## Epoch training
# TRAIN FOR 2 EPOCHS
for epoch in range(len(batch)):
    print(f'epoch {epoch+1}')
    for i,batch in enumerate(data_loader,1):
        print(f"Batch {i}:, x: {batch[0]} , y : {batch[1]}")

epoch 1
Batch 1:, x: tensor([[0.0611, 0.2246, 0.2343],
        [0.4609, 0.7084, 0.5798]], dtype=torch.float64) , y : tensor([0, 2])
Batch 2:, x: tensor([[0.1771, 0.5561, 0.1094],
        [0.4967, 0.5104, 0.3295]], dtype=torch.float64) , y : tensor([1, 3])
epoch 2
Batch 1:, x: tensor([[0.4967, 0.5104, 0.3295],
        [0.4609, 0.7084, 0.5798]], dtype=torch.float64) , y : tensor([3, 2])
Batch 2:, x: tensor([[0.0611, 0.2246, 0.2343],
        [0.1771, 0.5561, 0.1094]], dtype=torch.float64) , y : tensor([0, 1])
